codecov:
  require_ci_to_pass: true

notify:
  after_n_builds: 1

coverage:
  precision: 2
  round: down
  range: "50...100"
  status:
    project:
      default:
        target: auto          # compare to recent baseline
        threshold: 1%         # allow small fluctuation
        informational: false
    patch:
      default:
        target: 70%           # require reasonable coverage on changed lines
        threshold: 0.5%
        informational: false

comment:
  layout: "reach, diff, files, flags, footer"
  require_changes: false
  behavior: default

ignore:
  - "data-raw/**"
  - "inst/doc/**"
  - "vignettes/**"
  - "README.Rmd"
  - "man/**"
  - "docs/**"
