name: coverage
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr
      - name: Run tests & upload via covr
        run: Rscript -e 'covr::codecov(slug = "shmercer/writeAlizer", quiet = TRUE)'
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}  # needed for private repos; omit for public
