# .github/workflows/coverage.yaml
name: coverage
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr
      - name: Run tests & upload to Codecov via covr
        run: Rscript -e 'covr::codecov(quiet = TRUE)'
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}   # ✅ secret, not hardcoded
name: coverage
on:
  push:
    branches: [main, master]
  pull_request:
permissions: read-all

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr
          needs: check

      - name: Run tests and upload to Codecov
        run: Rscript -e 'covr::codecov()'
